DROP TABLE IF EXISTS Tweet CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Keyword CASCADE;

CREATE TABLE Users (
    login VARCHAR(20) PRIMARY KEY,
    active BOOLEAN NOT NULL,
    added TIMESTAMP NOT NULL,
    tweets INTEGER NOT NULL DEFAULT 0,
    lasttweetid BIGINT
);

CREATE TABLE Tweet (
    id BIGINT PRIMARY KEY,
    content VARCHAR(200) NOT NULL,
    userid VARCHAR(20) NOT NULL,
    date TIMESTAMP NOT NULL,
    lastup TIMESTAMP NOT NULL,
    favorites INTEGER NOT NULL DEFAULT 0,
    retweets INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (userid) REFERENCES Users
);

CREATE TABLE Keyword (
    content VARCHAR(200) PRIMARY KEY,
    occurences INTEGER NOT NULL,
    rate DOUBLE PRECISION DEFAULT 0
);
